spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: mall-portal
          uri: lb://mall-portal
          predicates:
            - Path=/mall-portal/**
          filters:
            - StripPrefix=1
            - Demo=GP-Mic
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.15:8761/eureka,http://192.168.1.16:8761/eureka
